### ISSUE TITLE
Upgrade formula

### ISSUE THREAD

**Issue by otavioschwanck** [daviderestivo/homebrew-emacs-head#100]
the lsp on m1 chip inst't work.

They already release the fix:
https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=b24c21e82ca0819f06ea5708274ce9091b3bc6d2

**Comment by daviderestivo** [comment]
@otavioschwanck, did you try to install emacs-head or emacs-head@28? I suggest to use emacs-head@28 for the M1 chip.

**Comment by otavioschwanck** [comment]
> @otavioschwanck, did you try to install emacs-head or emacs-head@28? I suggest to use emacs-head@28 for the M1 chip.

I'm already using emacs-head@28.

**Comment by daviderestivo** [comment]
@otavioschwanck: emacs-head@28 uses the emacs master branch (HEAD). So I guess you simply need to re-install since the fix you mentioned in the first message is already in. Or am I missing something?

**Comment by otavioschwanck** [comment]
> @otavioschwanck: emacs-head@28 uses the emacs master branch (HEAD). So I guess you simply need to re-install since the fix you mentioned in the first message is already in. Or am I missing something?

worked!

@daviderestivo the brew don't upgrade emacs head automatically ? i have to reinstall everytime i want to upgrade?

**Comment by daviderestivo** [comment]
> @daviderestivo the brew don't upgrade emacs head automatically ? i have to reinstall everytime i want to upgrade?

Yes exactly. Considering the master branch is sometimes broken it's even better that you have to explicitly reinstall :).

**Comment by daviderestivo** [comment]
If you're fine then please close this issue :)

**Comment by daviderestivo** [comment]
I closed this issue.
