### ISSUE TITLE
Easy way to swap icons

### ISSUE THREAD

**Issue by jmckitrick** [daviderestivo/homebrew-emacs-head#119]
I like to rotate my emacs app icon. Right now, I have to re-install the formula from scratch. Is there an easier way to re-install and just change the icon?

**Comment by daviderestivo** [comment]
Try to replace the `Emacs.icns` in`/usr/local/Cellar/emacs-head@28/28.0.50_1/Emacs.app/Contents/Resources`.

**Comment by jmckitrick** [comment]
Ok, that worked. Though it seemed to take several hours (overnight) to see the change.
