### ISSUE TITLE
Build issue 

### ISSUE THREAD

**Issue by jmckitrick** [daviderestivo/homebrew-emacs-head#120]
```
Building emacs-head@28 this morning gives this error:

Last 15 lines from /Users/jmckitrick/Library/Logs/Homebrew/emacs-head@28/03.make:
  GEN      ../../etc/charsets/CP949-2BYTE.map
  GEN      ../../etc/charsets/BIG5-1.map
  GEN      ../../etc/charsets/BIG5-2.map
  GEN      ../../etc/charsets/MULE-ethiopic.map
  GEN      ../../etc/charsets/MULE-ipa.map
  GEN      ../../etc/charsets/MULE-is13194.map
  GEN      ../../etc/charsets/MULE-sisheng.map
  GEN      ../../etc/charsets/MULE-tibetan.map
  GEN      ../../etc/charsets/MULE-lviscii.map
  GEN      ../../etc/charsets/MULE-uviscii.map
  GEN      ../../etc/charsets/GB180304.map
  GEN      ../../etc/charsets/JISX2131.map
  GEN      charsets.stamp
make: *** [src] Error 2
make: *** Waiting for unfinished jobs....

```

**Comment by daviderestivo** [comment]
This is probably an emacs upstream bug. Try tomorrow :)

**Comment by jmckitrick** [comment]
You were right, it was upstream. It worked yesterday. And it's broken again today, LOL.
Is there an easy way to tell whether it's upstream related or not?

**Comment by jmckitrick** [comment]
Ok, here's a new one, different from before:

Your branch is up to date with 'origin/master'.
HEAD is now at 55dda2571a Unbreak make bootstrap (don't use cl-defun's &aux parameters)
Error: undefined method `install_formula' for Homebrew::Upgrade:Module
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/install.rb:320:in `install_formula'
/usr/local/Homebrew/Library/Homebrew/install.rb:310:in `block in install_formulae'
/usr/local/Homebrew/Library/Homebrew/install.rb:309:in `each'
/usr/local/Homebrew/Library/Homebrew/install.rb:309:in `install_formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:206:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:129:in `<main>'

**Comment by jmckitrick** [comment]
All build issues are resolved now, but is there a simple way to tell if it's formula-based or upstream?

**Comment by daviderestivo** [comment]
I build everyday with GitHub CI Emacs 28 from Emacs master branch. You can try to have a look into the outcome. Alternatively you can setup your own CI. I close this bug.
