### ISSUE TITLE
Native comp on Emacs 29 does not seem to work

### ISSUE THREAD

**Issue by jmckitrick** [daviderestivo/homebrew-emacs-head#129]
I realize this could be user error, but in the interest of helping other users, I'd like to figure out what is going wrong, and contribute to improvements in the formula or the docs.

I build this formula once a week, and decided to try native comp for the first time. Everything seems fine until it loads, then the frame fills with error messages from libgccjit failures. I have a feeling it's a missing dependency, but I *thought* I got everything that was required. I'd like to figure out what I missed, and help document the issue for anyone else trying the same feature. I have gcc and libgccjit installed, so....

Here are the first few error messages:

```
Warning (initialization): An error occurred while loading ‘/Users/jmckitrick/.emacs.d/init.el’:

Native compiler error: (lambda (arg1 &optional) (let ((f #'yes-or-no-p)) (funcall f arg1))), Compiling /Users/jmckitrick/.emacs.d/eln-cache/28.0.60-3d05cc13/subr--trampoline-7965732d6f722d6e6f2d70_yes_or_no_p_0.eln...
ld: library not found for -lgcc_ext.10.5
libgccjit.so: error: error invoking gcc driver
Debugger entered--Lisp error: (native-ice "failed to compile" "/Users/jmckitrick/.emacs.d/eln-cache/28.0.60-3d05c..." "error invoking gcc driver")
  comp--compile-ctxt-to-file("/Users/jmckitrick/.emacs.d/eln-cache/28.0.60-3d05c...")
  comp-compile-ctxt-to-file("/Users/jmckitrick/.emacs.d/eln-cache/28.0.60-3d05c...")
  comp-final1()
  load-with-code-conversion("/private/var/folders/27/xs02f08d325_q2vh49wks48r00..." "/private/var/folders/27/xs02f08d325_q2vh49wks48r00..." nil t)
  command-line-1(("-l" "/var/folders/27/xs02f08d325_q2vh49wks48r0000gn/T/e..."))
  command-line()
  normal-top-level()

Warning (comp): libgccjit.so: error: error invoking gcc driver Disable showing Disable logging
Warning (comp): /usr/local/Cellar/emacs-head@28/28.0.50_1/share/emacs/28.0.60/lisp/url/url-vars.el.gz: Error: Internal native compiler error failed to compile Disable showing Disable logging
Warning (comp): libgccjit.so: error: error invoking gcc driver Disable showing Disable logging
Warning (comp): /usr/local/Cellar/emacs-head@28/28.0.50_1/share/emacs/28.0.60/lisp/password-cache.el.gz: Error: Internal native compiler error failed to compile Disable showing Disable logging

```

**Comment by jmckitrick** [comment]
Yep, I just tried the whole process again, with the same result. Very
frustrating.

Could it be a classpath or lib path issue?

**Comment by daviderestivo** [comment]
Do you have something in early-init.el? or did you set LIBRARY_PATH manually?

**Comment by jmckitrick** [comment]
No, nothing special. Emacs can find ripgrep, java, clojure, scala, etc.

**Comment by daviderestivo** [comment]
> No, nothing special. Emacs can find ripgrep, java, clojure, scala, etc.

Please share there output of `env` and the content of `early-init.el` :)

**Comment by jmckitrick** [comment]
<img width="1211" alt="Screen Shot 2021-10-17 at 2 49 37 PM" src="https://user-images.githubusercontent.com/518057/137640854-4d7ead5b-490f-46a7-8977-93ebb97cf09a.png">

Nothing in `early-init.el`

**Comment by jmckitrick** [comment]
Also, `exec-path`:

exec-path is a variable defined in ‘C source code’.

Its value is
("/usr/bin" "/bin" "/usr/sbin" "/sbin" "/usr/local/Cellar/emacs-head@29/29.0.50_1/libexec/emacs/29.0.50/x86_64-apple-darwin20.6.0")

**Comment by jmckitrick** [comment]
A user suggested I manually set CFLAGS or remove `-march=native`.

I've worked with Linux projects and autoconf a bit in the distant past, but I have not worked with brew formulae. How might I do this?

**Comment by jmckitrick** [comment]
Problem solved! I needed to run `brew edit` and remove the line with `-march=native` and everything worked fine after that.

**Comment by daviderestivo** [comment]
Fixed in https://github.com/daviderestivo/homebrew-emacs-head/pull/139. Please lemme know if it works for you.
