### ISSUE TITLE
@28 / @29 won't compile on M1 Macs without removing -march=native from the formula

### ISSUE THREAD

**Issue by mtwomey** [daviderestivo/homebrew-emacs-head#137]
As described in the title. I was able to work around this by manually editing the formula as described in #129.

**Comment by malcolmpurvis** [comment]
I can reproduce this in a brand new homebrew installation on Big Sur.  It appears that the native ARM compiler does not support the -march=native argument.

**Comment by daviderestivo** [comment]
I think that the CFLAGS can be removed completely. Lemme check the outcome of the CI :)

**Comment by daviderestivo** [comment]
Fixed in https://github.com/daviderestivo/homebrew-emacs-head/pull/139. Please lemme know if it works for you.

**Comment by jmckitrick** [comment]
I think we're good to go on this one.

**Comment by daviderestivo** [comment]
... then I'm gonna close this issue.
