### ISSUE TITLE
emacs 27.2 dies

### ISSUE THREAD

**Issue by algebravic** [daviderestivo/homebrew-emacs-head#141]
Every once in a while (it seems to happen when I moving files using tramp), emacs 27.2 will die with the error on the terminal:

`objc[66075]: Invalid or prematurely-freed autorelease pool 0x7f916c80e170.`

Suggestions as to debugging this?

**Comment by daviderestivo** [comment]
@algebravic I would suggest you open a bug report on emacs https://lists.gnu.org/mailman/listinfo/bug-gnu-emacs. There is not too much I can do here.

**Comment by daviderestivo** [comment]
@algebravic did you get a chance to open a bug report to emacs? I would be curious to know if a patch is available?

**Comment by algebravic** [comment]
Hi David, I never opened a bug report because I couldn’t come up with a
test case that would provoke the bug.  My suspicion is that it has to do
with tramp.  The crash has happened a few times since I reported it to you,
always when, or soon after I transfer a bunch of files from a remote Linux
system using tramp and scp.  But it doesn’t always happen.

Victor

**Comment by daviderestivo** [comment]
@algebravic if you agree I would close this issue since I don't think there is to much I can do here. Does the problem appear as well with Emacs 28?
