### ISSUE TITLE
Easy-kill no longer working correctly.

### ISSUE THREAD

**Issue by jmckitrick** [daviderestivo/homebrew-emacs-head#142]
After `M-w s` to select an sexp, hitting 's' again should select the next, and so on. This functionality is no longer working. Easy-kill upstream has not changed in quite some time.

This might be an upstream bug, but I'm not sure how to confirm that right now. I switched to @28 and everything is fine.

**Comment by daviderestivo** [comment]
@jmckitrick: by default `M-w` runs `kill-ring-save`. Which major/minor modes do you have enabled?

**Comment by jmckitrick** [comment]
I'm running `easy-kill` in this case. I'm in Clojure/CIDER or emacs lisp mode, and minor modes include:
Auto-Composition Auto-Compression Auto-Encryption
Auto-Revert Column-Number Delete-Selection Desktop-Save
Electric-Indent Emmet Eyebrowse File-Name-Shadow Font-Lock
Global-Eldoc Global-Font-Lock Global-Git-Commit Global-Hl-Line Ivy
Line-Number Magit-Auto-Revert Menu-Bar Minions Mouse-Wheel
Override-Global Projectile Recentf Save-Place Shell-Dirtrack
Show-Paren Transient-Mark Volatile-Highlights Which-Key Windmove

**Comment by jmckitrick** [comment]
https://github.com/leoliu/easy-kill

**Comment by jmckitrick** [comment]
It *seems* that this has been fixed. I'm doing more testing now.
Question: is there a way to use git bisect in this repo to narrow down the error and the fix?

**Comment by daviderestivo** [comment]
@jmckitrick sorry but I missed your question above. I do not think you can easily bisect using this formula :( You should someway do it manually ...
