### ISSUE TITLE
Emacs 28.1 has been released

### ISSUE THREAD

**Issue by seagle0128** [daviderestivo/homebrew-emacs-head#145]
Emacs 28.1 has been released. See https://lists.gnu.org/archive/html/emacs-devel/2022-04/msg00093.html. The receipt should be updated, I think. Thanks!

**Comment by daviderestivo** [comment]
@seagle0128: Just merged this PR https://github.com/daviderestivo/homebrew-emacs-head/pull/144 :)

**Comment by seagle0128** [comment]
Thank you for the quick response, @daviderestivo !
