### ISSUE TITLE
Emacs 29 with native comp fails on startup

### ISSUE THREAD

**Issue by jmckitrick** [daviderestivo/homebrew-emacs-head#149]
I build head 29 once a week. Last Friday, the build succeeded, but I got this error on startup, and every build since then:

~ ❯❯❯ emacs --debug-init
Error using execdir /opt/homebrew/Cellar/emacs-head@29/29.0.50_1/Emacs.app/Contents/MacOS/:
emacs: dlopen(/opt/homebrew/Cellar/emacs-head@29/29.0.50_1/Emacs.app/Contents/MacOS/../native-lisp/29.0.50-d356a56a/preloaded/window-0d1b8b93-0c17e2d3.eln, 0x0001): tried: '/opt/homebrew/Cellar/emacs-head@29/29.0.50_1/Emacs.app/Contents/MacOS/../native-lisp/29.0.50-d356a56a/preloaded/window-0d1b8b93-0c17e2d3.eln' (no such file)

I've tried deleting the `eln-cache` but get the same result.

I fall back to no native comp and it runs fine.

Here's my build command:

brew install emacs-head@29 --with-cocoa --with-modern-icon-dragon --with-no-frame-refocus --with-native-comp

**Comment by daviderestivo** [comment]
@jmckitrick Thanks for reporting it. I guess something changed in upstream but I didn't have any time to look into it.

**Comment by jmckitrick** [comment]
I see it could be related to this from a year ago:
https://github.com/d12frosted/homebrew-emacs-plus/issues/392

**Comment by jmckitrick** [comment]
This might be a possible solution:

https://github.com/d12frosted/homebrew-emacs-plus/issues/476#issuecomment-1177350063

**Comment by daviderestivo** [comment]
@jmckitrick I'm currently on holiday. Please make me a PR with the fix and I'm gonna merge it :)

**Comment by daviderestivo** [comment]
Thanks for the PR. I'm gonna run the CI and merge it if successful :)

**Comment by daviderestivo** [comment]
Merged into master.

**Comment by daviderestivo** [comment]
@jmckitrick i have added you to the contributor list :). Thanks for your help here. Appreciated :)
