### ISSUE TITLE
Question about upstream build issue

### ISSUE THREAD

**Issue by jmckitrick** [daviderestivo/homebrew-emacs-head#152]
It looks like emacs 29 on macOS is broken and has been for around a week or so. I don't see any discussion on emacs bugs or dev addressing it. I'm willing to do some test builds and poke around and help in the interesting of getting it working. Where should I start by offering my help? Is there a particular list I should post to?

**Comment by daviderestivo** [comment]
@jmckitrick I'm currently using emacs 29 on my Mac without any issue. What problem did you encounter? 

Anyway if you find a bug in Emacs then you should create a bug report and send it to https://lists.gnu.org/mailman/listinfo/bug-gnu-emacs.

**Comment by jmckitrick** [comment]
@daviderestivo I'm sorry about this... it looks like the issue was resolved. I promise, though, I was getting a broken build related to some ELC files. ;-)

Normally I would just watch the upstream builds and wait for a passing build, but based on this, I thought it was an ongoing issue:

https://hydra.nixos.org/job/gnu/emacs-trunk/build.x86_64-darwin/all
