### ISSUE TITLE
Is it ok to run `emacs --fg-daemon` and `emacs --bg-daemon` at the same time?

### ISSUE THREAD

**Issue by avatar-lavventura** [daviderestivo/homebrew-emacs-head#155]
I am trying to run `GNU Emacs 29.0.50` in `macOS`. The way install it as follows: 

```bash
brew reinstall emacs-head@29 --with-cocoa --with-native-full-aot --with-native-comp --with-dbus
```

The main problem I am having is emacs daemon consumes full-horse cpu power at the background.

---------------
I have observe that `Emacs --fg-daemon` and `Emacs --bg-daemon` processes are running at the same time. 

```bash
$ ps auxww | grep Emacs
alper  14481 100.0  0.4 34400312  71716   ??  R     2:48PM   0:02.35 /usr/local/Cellar/emacs-head@29/29.0.50_1/Emacs.app/Contents/MacOS/Emacs --fg-daemon
alper  12776   0.0  1.3 34563148 211120   ??  SNs   2:46PM   0:12.07 /usr/local/Cellar/emacs-head@29/29.0.50_1/Emacs.app/Contents/MacOS/Emacs --bg-daemon=\0123,4\012
```

The way I started emacs: `(&>/dev/null emacsclient -qut &)`

I was wondering is it fine that both `Emacs --fg-daemon` and `Emacs --bg-daemon` are running at the same time and do they cause extra cpu usage or both of them referring to the same daemon process?

Also asked: https://emacs.stackexchange.com/questions/73226/is-it-ok-to-run-emacs-fg-daemon-and-emacs-bg-daemon-at-the-same-time

**Comment by daviderestivo** [comment]
@avatar-lavventura from my understanding it seems you have two emacs daemon process running. Did you check if you have for example `brew` starting it in background? You can check using `brew services`.

**Comment by avatar-lavventura** [comment]
I was not able to figure out why this was happening. When I install emacs from its source-code the problem I was having is fixed.
