### ISSUE TITLE
Brew Services No Longer Working

### ISSUE THREAD

**Issue by dylanjm** [daviderestivo/homebrew-emacs-head#158]
Recently updated emacs and the homebrew formula. In the past I've set homebrew to launch the emacs-head@28 service so I can access emacsclient easily. I am now receiving this error when running `brew services start emacs-head@28` and I get this error in return:

```
Error: Formula `emacs-head@28` has not implemented #plist, #service or installed a locatable service file
```

**Comment by daviderestivo** [comment]
@dylanjm I will have a look and let you know.

**Comment by daviderestivo** [comment]
@dylanjm can you try to uninstall emacs-head@28 and reinstall it from scratch. Done that, can you please gimme the output of `brew services`. Thanks

**Comment by dylanjm** [comment]
I reinstalled emacs-head@28 with the following command:

```
brew install emacs-head@28 --with-cocoa --with-pdumper --with-no-frame-refocus --with-dbus --with-xwidgets --with-modern-icon-black-variant --with-mailutils --with-crash-debug --with-native-comp --with-native-full-aot
```

Here is the output of `brew services`:

```
Name          Status  User   File
dbus          stopped mcdodj ~/Library/LaunchAgents/org.freedesktop.dbus-session.plist
emacs         none
emacs-head@28 none
goku          none
isync         none
mopidy        none
unbound       none
vdirsyncer    none
yabai         none
```

**Comment by daviderestivo** [comment]
@dylanjm I assume that after reinstallation you have the same issue.

I tried on my two boxes (one running Catalina and another one running Monterey). On both of them it seems to work as expected:


```
$ brew install emacs-head@28 --with-cocoa --with-pdumper --with-no-frame-refocus --with-dbus --with-xwidgets --with-modern-icon-black-variant --with-mailutils --with-crash-debug --with-native-comp --with-native-full-aot

$ brew services
Name          Status User File
dbus          none
emacs-head@28 none
kafka         none
unbound       none
zookeeper     none

$ brew services start emacs-head@28
==> Successfully started `emacs-head@28` (label: homebrew.mxcl.emacs-head@28)

$ brew services
Name          Status  User   File
dbus          none
emacs-head@28 started gutter ~/Library/LaunchAgents/homebrew.mxcl.emacs-head@28.plist
kafka         none
unbound       none
zookeeper     none

$ ps -ef | grep emacs
  501 52018     1   0 10:13AM ??         0:01.49 /usr/local/Cellar/emacs-head@28/28.2_1/Emacs.app/Contents/MacOS/Emacs --fg-daemon
```

**Comment by dylanjm** [comment]
Ahh okay, I uninstalled it one more time and tried again and now it's working. I'm not sure what exactly happened. I had some linking issues before. I also had to update xcode command line tools recently, so not sure if that put my machine in a weird state. I'll go ahead and close this issue. I appreciate your time! Thank you!

**Comment by daviderestivo** [comment]
@dylanjm thanks to you :) ... have fun!
