### ISSUE TITLE
Native Treesitter build support for emacs@29 and emacs@30

### ISSUE THREAD

**Issue by malcolmpurvis** [daviderestivo/homebrew-emacs-head#162]
Building the new built-in treesitter support requires passing in the `--with-tree-sitter` option to configure. Could this option be added to the Brewfile and passed in?

Thanks.

**Comment by daviderestivo** [comment]
Hi @malcolmpurvis, 

sure I will add it. It's already in my TODO list.

Regards,
Davide

**Comment by daviderestivo** [comment]
Hi @malcolmpurvis,

Tree-sitter support is ready: https://github.com/daviderestivo/homebrew-emacs-head/pull/165. 
Once CI is successful I will merge it into master.

Regards,
Davide

**Comment by daviderestivo** [comment]
@malcolmpurvis Tree-sitter is not on master. Please have a look into it :)

Regards,
Davide
