### ISSUE TITLE
:recommend keyword problem

### ISSUE THREAD

**Issue by liuyinz** [daviderestivo/homebrew-emacs-head#166]
Since change dependency to :recommend, some features failed.
e.g. --with-librsvg failed, var `image-types` doesn't include svg even if it's enabled by default.

**Comment by daviderestivo** [comment]
Thanks for spotting this issue. I will have a look asap.

**Comment by daviderestivo** [comment]
@liuyinz can you please attach a complete installation output that failed?

**Comment by liuyinz** [comment]
Installation, dependency of `librsvg` has installed.

``` shell
brew install emacs-head@29 --with-cocoa --with-mailutils --with-imagemagick --with-xwidgets --with-tree-sitter
```

Emacs configuration
``` 
In GNU Emacs 29.0.60 (build 2, x86_64-apple-darwin21.6.0, NS
 appkit-2113.60 Version 12.6.2 (Build 21G320)) of 2023-01-13 built on
 192.168.0.102
Windowing system distributor 'Apple', version 10.3.2113
System Description:  macOS 12.6.2

Configured using:
 'configure --enable-locallisppath=/usr/local/share/emacs/site-lisp
 --infodir=/usr/local/Cellar/emacs-head@29/29.0.60_1/share/info/emacs
 --prefix=/usr/local/Cellar/emacs-head@29/29.0.60_1 --without-x
 --without-dbus --with-imagemagick --with-modules --without-pop
 --with-gnutls --with-rsvg --with-xml2 --with-xwidgets --with-ns
 --disable-ns-self-contained 'CFLAGS=-DFD_SETSIZE=10000
 -DDARWIN_UNLIMITED_SELECT''

Configured features:
ACL GIF GMP GNUTLS IMAGEMAGICK JPEG JSON LCMS2 LIBXML2 MODULES NOTIFY
KQUEUE NS PDUMPER PNG SQLITE3 THREADS TIFF TOOLKIT_SCROLL_BARS
TREE_SITTER WEBP XIM XWIDGETS ZLIB
```

But doesn't support svg image
``` emacs-lisp
;; test
image-types
=> (heic imagemagick webp png gif tiff jpeg xpm xbm pbm) don't include svg

(image-type-available-p 'svg)
=> nil 
```

**Comment by liuyinz** [comment]
@daviderestivo  I will install in again and provide a complete installation output later.

**Comment by liuyinz** [comment]
brew install emacs-head@29 --with-cocoa --with-mailutils --with-imagemagick --with-xwidgets --with-tree-sitter
==> Fetching daviderestivo/emacs-head/emacs-head@29
==> Downloading https://raw.githubusercontent.com/daviderestivo/homebrew-emacs-head/master/patches/0005-System-appearance.patch
Already downloaded: /Users/ray/Library/Caches/Homebrew/downloads/aedf6bcffeb3a805dd1feae35654986fa3062c6d42dd2ccc6e9f105bf60e1db1--0005-System-appearance.patch
==> Downloading https://raw.githubusercontent.com/daviderestivo/homebrew-emacs-head/master/patches/0008-Fix-window-role.patch
Already downloaded: /Users/ray/Library/Caches/Homebrew/downloads/aa727383a475fe50cd4aa2fdcce43dc2ca41fdf5e3518a2171dbc236c2a1b9c7--0008-Fix-window-role.patch
==> Downloading https://raw.githubusercontent.com/daviderestivo/homebrew-emacs-head/master/patches/0001-No-frame-refocus-cocoa.patch
Already downloaded: /Users/ray/Library/Caches/Homebrew/downloads/9aa035e80d3ab084120a4788c3ebbe29aab330a221dcbc92b8017a51c2ea5aa4--0001-No-frame-refocus-cocoa.patch
==> Downloading https://raw.githubusercontent.com/daviderestivo/homebrew-emacs-head/master/patches/0003-Pdumper-size-increase.patch
Already downloaded: /Users/ray/Library/Caches/Homebrew/downloads/48b7b584452aaa782a33329cf34cea430a07ab987d772eeb06900e0903f444b1--0003-Pdumper-size-increase.patch
==> Downloading https://raw.githubusercontent.com/daviderestivo/homebrew-emacs-head/master/patches/0005-System-appearance.patch
Already downloaded: /Users/ray/Library/Caches/Homebrew/downloads/aedf6bcffeb3a805dd1feae35654986fa3062c6d42dd2ccc6e9f105bf60e1db1--0005-System-appearance.patch
==> Downloading https://raw.githubusercontent.com/daviderestivo/homebrew-emacs-head/master/patches/0008-Fix-window-role.patch
Already downloaded: /Users/ray/Library/Caches/Homebrew/downloads/aa727383a475fe50cd4aa2fdcce43dc2ca41fdf5e3518a2171dbc236c2a1b9c7--0008-Fix-window-role.patch
==> Downloading https://raw.githubusercontent.com/daviderestivo/homebrew-emacs-head/master/icons/modern-icon-sjrmanning.icns
Already downloaded: /Users/ray/Library/Caches/Homebrew/downloads/39d0fe298a426f0e8cde2cb6708c66c5f1bfbfbc3252830bf8cfa1cea516ac39--modern-icon-sjrmanning.icns
==> Downloading https://raw.githubusercontent.com/daviderestivo/homebrew-emacs-head/master/icons/modern-icon-asingh4242.icns
Already downloaded: /Users/ray/Library/Caches/Homebrew/downloads/c877a9e9414a3c6ebc1ed777f76113578b9dc9ff6faf6ab530bba2a58785d457--modern-icon-asingh4242.icns
==> Downloading https://raw.githubusercontent.com/daviderestivo/homebrew-emacs-head/master/icons/modern-icon-paper-icons.icns
Already downloaded: /Users/ray/Library/Caches/Homebrew/downloads/343e3f5094d0a762d783a49410810d104241ae842756399e202dbf00c1087ed6--modern-icon-paper-icons.icns
==> Downloading https://raw.githubusercontent.com/daviderestivo/homebrew-emacs-head/master/icons/modern-icon-azhilin.icns
Already downloaded: /Users/ray/Library/Caches/Homebrew/downloads/97bcc6ed80cd2abe0e0494b549402b01c724f5c19e814814cd4364c23e48d9dc--modern-icon-azhilin.icns
==> Downloading https://raw.githubusercontent.com/daviderestivo/homebrew-emacs-head/master/icons/modern-icon-mzaplotnik.icns
Already downloaded: /Users/ray/Library/Caches/Homebrew/downloads/fbbaea5282b20d3da5b2b657cd7a2e51feb8c512d4b323ee5fd3fdb150227f23--modern-icon-mzaplotnik.icns
==> Downloading https://raw.githubusercontent.com/daviderestivo/homebrew-emacs-head/master/icons/modern-icon-bananxan.icns
Already downloaded: /Users/ray/Library/Caches/Homebrew/downloads/3e94adecdb53e2b55f8aa000f1ee07037b8184cfc2d3a02e24514aecdd2e31c2--modern-icon-bananxan.icns
==> Downloading https://raw.githubusercontent.com/daviderestivo/homebrew-emacs-head/master/icons/modern-icon-vscode.icns
Already downloaded: /Users/ray/Library/Caches/Homebrew/downloads/58092241f466f380780d495922401e57e42f1bcf366a6284eded12f33c5b2a2e--modern-icon-vscode.icns
==> Downloading https://raw.githubusercontent.com/daviderestivo/homebrew-emacs-head/master/icons/modern-icon-sexy-v1.icns
Already downloaded: /Users/ray/Library/Caches/Homebrew/downloads/c25a8c4e80563d8e11e4be87118e3923ae25654efe25b2e5dc4f4a7e301f3169--modern-icon-sexy-v1.icns
==> Downloading https://raw.githubusercontent.com/daviderestivo/homebrew-emacs-head/master/icons/modern-icon-sexy-v2.icns
Already downloaded: /Users/ray/Library/Caches/Homebrew/downloads/eb68e5f126b77164faf3bb606c9f03198f3940c57e9791337368075ea97275cc--modern-icon-sexy-v2.icns
==> Downloading https://raw.githubusercontent.com/daviderestivo/homebrew-emacs-head/master/icons/modern-icon-cg433n.icns
Already downloaded: /Users/ray/Library/Caches/Homebrew/downloads/dd4b6ae1b381a861af54d3c8a6acf46b8fadcb7f91f0644fea728dbc7b09a7a6--modern-icon-cg433n.icns
==> Downloading https://raw.githubusercontent.com/daviderestivo/homebrew-emacs-head/master/icons/modern-icon-purple.icns
Already downloaded: /Users/ray/Library/Caches/Homebrew/downloads/4ab976c47b420e8de2d3ba39a0698db791b2f7a220495c2ac9295a83a66b56d4--modern-icon-purple.icns
==> Downloading https://raw.githubusercontent.com/daviderestivo/homebrew-emacs-head/master/icons/modern-icon-yellow.icns
Already downloaded: /Users/ray/Library/Caches/Homebrew/downloads/6263eff5a8e7abea09ad64a37a6c70fe704f9adf2638a7028bde43807e5dbee6--modern-icon-yellow.icns
==> Downloading https://raw.githubusercontent.com/daviderestivo/homebrew-emacs-head/master/icons/modern-icon-orange.icns
Already downloaded: /Users/ray/Library/Caches/Homebrew/downloads/0b466a756efe093de549aa5be09885e5d93831289aca7837ec4998e5bc21d82a--modern-icon-orange.icns
==> Downloading https://raw.githubusercontent.com/daviderestivo/homebrew-emacs-head/master/icons/modern-icon-papirus.icns
Already downloaded: /Users/ray/Library/Caches/Homebrew/downloads/b0631e905c0a74dd97a8b89ffdab8a48d52b60b54d4aba74d5e20f97a22bcecc--modern-icon-papirus.icns
==> Downloading https://raw.githubusercontent.com/daviderestivo/homebrew-emacs-head/master/icons/modern-icon-pen.icns
Already downloaded: /Users/ray/Library/Caches/Homebrew/downloads/11054112a8202dcb9c7354a96fece544781992fe48d264feeb9755ef68d6b306--modern-icon-pen.icns
==> Downloading https://raw.githubusercontent.com/daviderestivo/homebrew-emacs-head/master/icons/modern-icon-pen-3d.icns
Already downloaded: /Users/ray/Library/Caches/Homebrew/downloads/5de19dbeabaf9e983dd53845a6d42fad570bddb020684d5fe98b97820d74a183--modern-icon-pen-3d.icns
==> Downloading https://raw.githubusercontent.com/daviderestivo/homebrew-emacs-head/master/icons/modern-icon-pen-lds56.icns
Already downloaded: /Users/ray/Library/Caches/Homebrew/downloads/c77337e4762d6cc15b868ba113e1d6638299b24b314428306155c6881ee9c779--modern-icon-pen-lds56.icns
==> Downloading https://raw.githubusercontent.com/daviderestivo/homebrew-emacs-head/master/icons/modern-icon-pen-black.icns
Already downloaded: /Users/ray/Library/Caches/Homebrew/downloads/d3c8e46c2e9a0a575a1d54d6bbaac80ace4510d31a893e7c778faf036bb2fa38--modern-icon-pen-black.icns
==> Downloading https://raw.githubusercontent.com/daviderestivo/homebrew-emacs-head/master/icons/modern-icon-black-variant.icns
Already downloaded: /Users/ray/Library/Caches/Homebrew/downloads/25a434cdb031d69bac634fc2c8c7199722d99c45d8fed7f8e2b552eb6e78644a--modern-icon-black-variant.icns
==> Downloading https://raw.githubusercontent.com/daviderestivo/homebrew-emacs-head/master/icons/modern-icon-purple-flat.icns
Already downloaded: /Users/ray/Library/Caches/Homebrew/downloads/7255e8dd88a5df2807ed4cf8850c95479b3bdab5bc1cac2bb21f1d43329f10da--modern-icon-purple-flat.icns
==> Downloading https://raw.githubusercontent.com/daviderestivo/homebrew-emacs-head/master/icons/modern-icon-spacemacs.icns
Already downloaded: /Users/ray/Library/Caches/Homebrew/downloads/3df79863c8943c90e4c089eef607ccc1bbc7fef3143450ba4c6179e92b53f3d4--modern-icon-spacemacs.icns
==> Downloading https://raw.githubusercontent.com/daviderestivo/homebrew-emacs-head/master/icons/modern-icon-alecive-flatwoken.icns
Already downloaded: /Users/ray/Library/Caches/Homebrew/downloads/8f9609e71af8cb913022b1bcb28dac0db9edeee72079f1a519174ea60ec3a38c--modern-icon-alecive-flatwoken.icns
==> Downloading https://raw.githubusercontent.com/daviderestivo/homebrew-emacs-head/master/icons/modern-icon-elrumo1.icns
Already downloaded: /Users/ray/Library/Caches/Homebrew/downloads/00821af1ff9fdc0b2dfe5ed5103e0017fe230ae395abdfe8e202d4f6b1564114--modern-icon-elrumo1.icns
==> Downloading https://raw.githubusercontent.com/daviderestivo/homebrew-emacs-head/master/icons/modern-icon-elrumo2.icns
Already downloaded: /Users/ray/Library/Caches/Homebrew/downloads/37419ae70a2c4e5d6d9bbad9ef79be30dc190fe1c7ab1c042c923ba0c8dc9091--modern-icon-elrumo2.icns
==> Downloading https://raw.githubusercontent.com/daviderestivo/homebrew-emacs-head/master/icons/modern-icon-bokehlicia-captiva.icns
Already downloaded: /Users/ray/Library/Caches/Homebrew/downloads/519b8d66a63aad4320ce61c428be2fe6e3a7938185c18d1c45f8432514b7e9b8--modern-icon-bokehlicia-captiva.icns
==> Downloading https://raw.githubusercontent.com/daviderestivo/homebrew-emacs-head/master/icons/modern-icon-nuvola.icns
Already downloaded: /Users/ray/Library/Caches/Homebrew/downloads/ad0987aea7f806ceddc46127d0ca7c5c3f4335c0518cb8c166c514d54f92715a--modern-icon-nuvola.icns
==> Downloading https://raw.githubusercontent.com/daviderestivo/homebrew-emacs-head/master/icons/modern-icon-black-gnu-head.icns
Already downloaded: /Users/ray/Library/Caches/Homebrew/downloads/b86eff55a067ce936b740b8ef557f6fae11b4998fc072f9deca895e35bdc6450--modern-icon-black-gnu-head.icns
==> Downloading https://raw.githubusercontent.com/daviderestivo/homebrew-emacs-head/master/icons/modern-icon-dragon.icns
Already downloaded: /Users/ray/Library/Caches/Homebrew/downloads/ccba83222ca728c23089279db80c219652c1e55defcdfe51d0becbc5c2384ea2--modern-icon-dragon.icns
==> Downloading https://raw.githubusercontent.com/daviderestivo/homebrew-emacs-head/master/icons/modern-icon-black-dragon.icns
Already downloaded: /Users/ray/Library/Caches/Homebrew/downloads/ac0148c1c70515224d5748914b255293f96a1497d7150b7705006c9f4134f67a--modern-icon-black-dragon.icns
==> Downloading https://raw.githubusercontent.com/daviderestivo/homebrew-emacs-head/master/icons/modern-icon-EmacsIcon1.icns
Already downloaded: /Users/ray/Library/Caches/Homebrew/downloads/c64defa4b81d90e9ed0fd3f15d80d6e1e49b3cac0c5de72c9cbe7c12df8b6073--modern-icon-EmacsIcon1.icns
==> Downloading https://raw.githubusercontent.com/daviderestivo/homebrew-emacs-head/master/icons/modern-icon-EmacsIcon2.icns
Already downloaded: /Users/ray/Library/Caches/Homebrew/downloads/50bb6e41b7926d0ddeca6574e352e7953fc1cc5afa8bfee332bea3785f4be61d--modern-icon-EmacsIcon2.icns
==> Downloading https://raw.githubusercontent.com/daviderestivo/homebrew-emacs-head/master/icons/modern-icon-EmacsIcon3.icns
Already downloaded: /Users/ray/Library/Caches/Homebrew/downloads/d0de2cb84a004f80a5a9b91bdcd424dd17a9c4cb2bc0700c3b87d2025bd5e1d9--modern-icon-EmacsIcon3.icns
==> Downloading https://raw.githubusercontent.com/daviderestivo/homebrew-emacs-head/master/icons/modern-icon-EmacsIcon4.icns
Already downloaded: /Users/ray/Library/Caches/Homebrew/downloads/34955ff22a82df7bbad3106fb0afbd27095285511059c2f28fea67dcb8d27755--modern-icon-EmacsIcon4.icns
==> Downloading https://raw.githubusercontent.com/daviderestivo/homebrew-emacs-head/master/icons/modern-icon-EmacsIcon5.icns
Already downloaded: /Users/ray/Library/Caches/Homebrew/downloads/e7f852cfbcae69af8ba5d689022eb8ff5940dee856d340ec430a3a0788e6fa3e--modern-icon-EmacsIcon5.icns
==> Downloading https://raw.githubusercontent.com/daviderestivo/homebrew-emacs-head/master/icons/modern-icon-EmacsIcon6.icns
Already downloaded: /Users/ray/Library/Caches/Homebrew/downloads/0d349b9b0320e8220002e92c616ddc159ff10ac6e4daf32e4acde65e77a19f04--modern-icon-EmacsIcon6.icns
==> Downloading https://raw.githubusercontent.com/daviderestivo/homebrew-emacs-head/master/icons/modern-icon-EmacsIcon7.icns
Already downloaded: /Users/ray/Library/Caches/Homebrew/downloads/713789781c7fa008af9f9320ecb2c61f387ec1893e21afadd8f82073fcf93362--modern-icon-EmacsIcon7.icns
==> Downloading https://raw.githubusercontent.com/daviderestivo/homebrew-emacs-head/master/icons/modern-icon-EmacsIcon8.icns
Already downloaded: /Users/ray/Library/Caches/Homebrew/downloads/977e9c79b3e3ce2b750b54aee07db58d0cc8e0fe8d9cfff379b4cc2e4c3d5eec--modern-icon-EmacsIcon8.icns
==> Downloading https://raw.githubusercontent.com/daviderestivo/homebrew-emacs-head/master/icons/modern-icon-EmacsIcon9.icns
Already downloaded: /Users/ray/Library/Caches/Homebrew/downloads/a660c6100ace3343d89984040b47df048ef71c66f3631c056e6e3a784cb31c7e--modern-icon-EmacsIcon9.icns
==> Downloading https://raw.githubusercontent.com/daviderestivo/homebrew-emacs-head/master/icons/modern-icon-emacs-card-blue-deep.icns
Already downloaded: /Users/ray/Library/Caches/Homebrew/downloads/aecb8bc82c34141abd1cb7020da86ba3ac59a99b58f5adfea67c3b5febae7f2a--modern-icon-emacs-card-blue-deep.icns
==> Downloading https://raw.githubusercontent.com/daviderestivo/homebrew-emacs-head/master/icons/modern-icon-emacs-card-british-racing-green.icns
Already downloaded: /Users/ray/Library/Caches/Homebrew/downloads/2ccd6eba8873fe56038721feafc5383921b08e03b71fb2bc46ebc8549310565a--modern-icon-emacs-card-british-racing-green.icns
==> Downloading https://raw.githubusercontent.com/daviderestivo/homebrew-emacs-head/master/icons/modern-icon-emacs-card-carmine.icns
Already downloaded: /Users/ray/Library/Caches/Homebrew/downloads/858b6aac13c43939e3df25157cff4005594d328555af102d2bd8eb8f6234c87f--modern-icon-emacs-card-carmine.icns
==> Downloading https://raw.githubusercontent.com/daviderestivo/homebrew-emacs-head/master/icons/modern-icon-emacs-card-green.icns
Already downloaded: /Users/ray/Library/Caches/Homebrew/downloads/506d5435c70c47190a4eac36e8c790a1c30f74601cea200aa44fd59cbf5393ad--modern-icon-emacs-card-green.icns
==> Downloading https://raw.githubusercontent.com/daviderestivo/homebrew-emacs-head/master/icons/modern-icon-doom.icns
Already downloaded: /Users/ray/Library/Caches/Homebrew/downloads/43596c24fa2ed159515321214da1391a523b4492d90a6aefdca8cab805ffdfdc--modern-icon-doom.icns
==> Downloading https://raw.githubusercontent.com/daviderestivo/homebrew-emacs-head/master/icons/modern-icon-doom3.icns
Already downloaded: /Users/ray/Library/Caches/Homebrew/downloads/4fd20512aab50bc68954c06bfa3b82f6d128c927d74b3a751dc4a0570d4c71d8--modern-icon-doom3.icns
==> Downloading https://raw.githubusercontent.com/daviderestivo/homebrew-emacs-head/master/icons/modern-icon-doom-cacodemon.icns
Already downloaded: /Users/ray/Library/Caches/Homebrew/downloads/d77353ceea024ae4dfe4e4708c860aa4bc4de3cf98b4ea727cc5fe12c6717e65--modern-icon-doom-cacodemon.icns
==> Downloading https://raw.githubusercontent.com/daviderestivo/homebrew-emacs-head/master/icons/retro-icon-emacs-logo.icns
Already downloaded: /Users/ray/Library/Caches/Homebrew/downloads/dc8221d1e425a535cb2b753e3bc684c44567ea4ae1d94f331efd8d6364f65907--retro-icon-emacs-logo.icns
==> Downloading https://raw.githubusercontent.com/daviderestivo/homebrew-emacs-head/master/icons/retro-icon-gnu-head.icns
Already downloaded: /Users/ray/Library/Caches/Homebrew/downloads/e82d6686127bddc6d9cd068ae33a4692d1124f7a79c7c69657707fdc1342def0--retro-icon-gnu-head.icns
==> Downloading https://raw.githubusercontent.com/daviderestivo/homebrew-emacs-head/master/icons/retro-icon-gnu-meditate-levitate.icns
Already downloaded: /Users/ray/Library/Caches/Homebrew/downloads/b4a2c99b5e1bc4f7df7937b6b171e4c234a4f069cc6cc8eff9841ee00e83db47--retro-icon-gnu-meditate-levitate.icns
==> Downloading https://raw.githubusercontent.com/daviderestivo/homebrew-emacs-head/master/icons/retro-icon-sink-bw.icns
Already downloaded: /Users/ray/Library/Caches/Homebrew/downloads/512332bcde569f5396f4d85806df9a23a0f10a21950aa131c7cd5ba5f3134b7d--retro-icon-sink-bw.icns
==> Downloading https://raw.githubusercontent.com/daviderestivo/homebrew-emacs-head/master/icons/retro-icon-sink.icns
Already downloaded: /Users/ray/Library/Caches/Homebrew/downloads/ed73bc4a65ab25c086da0d5271d025a444b448505fbd1e739db6be58c372894d--retro-icon-sink.icns
==> Cloning https://github.com/emacs-mirror/emacs.git
Updating /Users/ray/Library/Caches/Homebrew/emacs-head@29--git
==> Checking out branch emacs-29
Already on 'emacs-29'
Your branch is up to date with 'origin/emacs-29'.
HEAD is now at c6bbf9cc27 Add c-ts-mode tests
==> Installing emacs-head@29 from daviderestivo/emacs-head
==> Patching
==> Applying 0005-System-appearance.patch
patching file src/frame.h
patching file src/nsfns.m
Hunk #1 succeeded at 1386 (offset 130 lines).
patching file src/nsterm.m
Hunk #1 succeeded at 1932 (offset 43 lines).
Hunk #2 succeeded at 5786 (offset 391 lines).
Hunk #3 succeeded at 6074 (offset 433 lines).
Hunk #4 succeeded at 6124 (offset 433 lines).
Hunk #5 succeeded at 6353 (offset 436 lines).
Hunk #6 succeeded at 9776 (offset 874 lines).
Hunk #7 succeeded at 11110 (offset 1052 lines).
==> Applying 0008-Fix-window-role.patch
patching file src/nsterm.m
Hunk #1 succeeded at 9540 (offset 772 lines).
==> ImageMagick PKG_CONFIG_PATH: 
/usr/local/opt/imagemagick/lib/pkgconfig
==> ./autogen.sh
==> ./configure --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-head@29/29.0.60_1/share/info/emacs --prefix=/usr/local/Cellar/emacs-head@2
==> make
==> make install
==> Caveats
Emacs.app was installed to:
  /usr/local/opt/emacs-head@29
To link the application:
  ln -s /usr/local/opt/emacs-head@29/Emacs.app /Applications


To start daviderestivo/emacs-head/emacs-head@29 now and restart at login:
  brew services start daviderestivo/emacs-head/emacs-head@29
Or, if you don't want/need a background service you can just run:
  emacs
==> Summary
🍺  /usr/local/Cellar/emacs-head@29/29.0.60_1: 4,200 files, 146.4MB, built in 6 minutes 52 seconds

**Comment by daviderestivo** [comment]
@liuyinz  I have tried on my box but I cannot replicate your issue. Please see below:

```console
$ brew uninstall --ignore-dependencies librsvg
Uninstalling /usr/local/Cellar/librsvg/2.55.1... (24 files, 56.5MB)

$ brew install emacs-head@29 --with-cocoa --with-mailutils --with-imagemagick --with-xwidgets --with-tree-sitter
==> Fetching dependencies for daviderestivo/emacs-head/emacs-head@29: librsvg and tree-sitter
==> Fetching librsvg
==> Downloading https://ghcr.io/v2/homebrew/core/librsvg/manifests/2.55.1
Already downloaded: /Users/gutter/Library/Caches/Homebrew/downloads/82a4ba5f6a95ae105bdcbea15c2199be17506493b277a9378a297d2d221c918f--librsvg-2.55.1.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/librsvg/blobs/sha256:491d993ed584eb8c4e2c7e3818ff871b38783fa6ed076233fc93d5546e55f038
Already downloaded: /Users/gutter/Library/Caches/Homebrew/downloads/6936319502d43478143026276a683c1aae1a3cf0eb63b559dd0e689deda5a26c--librsvg--2.55.1.catalina.bottle.tar.gz
==> Fetching tree-sitter
[CUT]
```

``` elisp
$ emacs -nw
  1 *** Welcome to IELM ***  Type (describe-mode) or press h for help.
  2 ELISP> (image-type-available-p 'svg)
  3 t
  4 ELISP> system-configuration-options
  5 "--enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-head@29/29.0.60_1/share/info/emacs --prefix=/usr/local/Cellar/emacs-head@29/29.0.60_1 --without-x
    --without-dbus --with-imagemagick --with-modules --without-pop --with-gnutls --with-rsvg --with-xml2 --with-xwidgets --with-ns --disable-ns-self-contained 'CFLAGS=-DFD_SETSIZE=10000
    -DDARWIN_UNLIMITED_SELECT'"
  6 ELISP> (emacs-version)
  7 "GNU Emacs 29.0.60 (build 2, x86_64-apple-darwin19.6.0, NS appkit-1894.70 Version 10.15.7 (Build 19H2026))
  8  of 2023-01-13"
  9 ELISP>
```

**Comment by liuyinz** [comment]
@daviderestivo same installation as you, but still failed. Here is my install output, could you find the problem ? or maybe my brew config treat :recommend keyword behavior differently? Perhaps I should try commit several months before.
```
=> Cloning https://github.com/emacs-mirror/emacs.git
Updating /Users/ray/Library/Caches/Homebrew/emacs-head@29--git
From https://github.com/emacs-mirror/emacs
   c6bbf9cc27..861556c133  emacs-29   -> origin/emacs-29
==> Checking out branch emacs-29
Already on 'emacs-29'
Your branch is behind 'origin/emacs-29' by 2 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
HEAD is now at 861556c133 Fix minibuffer-completion tests
==> Installing emacs-head@29 from daviderestivo/emacs-head
==> Installing dependencies for daviderestivo/emacs-head/emacs-head@29: librsvg
==> Installing daviderestivo/emacs-head/emacs-head@29 dependency: librsvg
==> Pouring librsvg--2.55.1.monterey.bottle.tar.gz
==> /usr/local/opt/gdk-pixbuf/bin/gdk-pixbuf-query-loaders --update-cache
🍺  /usr/local/Cellar/librsvg/2.55.1: 24 files, 56.5MB
==> Installing daviderestivo/emacs-head/emacs-head@29 --with-mailutils --with-co
==> Patching
==> Applying 0005-System-appearance.patch
patching file src/frame.h
patching file src/nsfns.m
Hunk #1 succeeded at 1386 (offset 130 lines).
patching file src/nsterm.m
Hunk #1 succeeded at 1932 (offset 43 lines).
Hunk #2 succeeded at 5786 (offset 391 lines).
Hunk #3 succeeded at 6074 (offset 433 lines).
Hunk #4 succeeded at 6124 (offset 433 lines).
Hunk #5 succeeded at 6353 (offset 436 lines).
Hunk #6 succeeded at 9776 (offset 874 lines).
Hunk #7 succeeded at 11110 (offset 1052 lines).
==> Applying 0008-Fix-window-role.patch
patching file src/nsterm.m
Hunk #1 succeeded at 9540 (offset 772 lines).
==> ImageMagick PKG_CONFIG_PATH: 
/usr/local/opt/imagemagick/lib/pkgconfig
==> ./autogen.sh
==> ./configure --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/loc
==> make
==> make install
==> Caveats
Emacs.app was installed to:
  /usr/local/opt/emacs-head@29
To link the application:
  ln -s /usr/local/opt/emacs-head@29/Emacs.app /Applications
```

**Comment by daviderestivo** [comment]
@liuyinz. Try to remove the git repo:

```
rm -Rf /Users/ray/Library/Caches/Homebrew/emacs-head@29--git
```

**Comment by liuyinz** [comment]
The bug should be here, https://debbugs.gnu.org/cgi/bugreport.cgi?bug=59081
It seems macos version close to 13 vertura and emacs version lower than 29.1 would has the problem.
