### ISSUE TITLE
warning in install emacs-head

### ISSUE THREAD

**Issue by liuyinz** [daviderestivo/homebrew-emacs-head#167]
Warning: Calling plist_options is deprecated! Use service.require_root instead.
Please report this issue to the daviderestivo/emacs-head tap (not Homebrew/brew or Homebrew/homebrew-core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/daviderestivo/homebrew-emacs-head/Formula/emacs-head@29.rb:679

**Comment by daviderestivo** [comment]
Fixed in https://github.com/daviderestivo/homebrew-emacs-head/pull/168
