### ISSUE TITLE
Error running make during installation on macOS 13.5 - "make all" failed with exit status 2.

### ISSUE THREAD

**Issue by louisdecharson** [daviderestivo/homebrew-emacs-head#179]
Hi @daviderestivo,

First thank you for doing this great work !

I'm having the following error when running the following command:
<details><summary>Error log</summary><pre>
Last 15 lines from /Users/Louis_de_Charsonville/Library/Logs/Homebrew/emacs-head@29/03.make:
make[3]: *** [gnus/gnus-async.elc] Error 255
dbus[48691]: Dynamic session lookup supported but failed: launchd did not provide a socket path, verify that org.freedesktop.dbus-session.plist is loaded!
dbus[48689]: Dynamic session lookup supported but failed: launchd did not provide a socket path, verify that org.freedesktop.dbus-session.plist is loaded!
make[2]: *** [compile-main] Error 2
make[1]: *** [lisp] Error 2
***
*** "make all" failed with exit status 2.
***
*** You could try to:
*** - run "make bootstrap", which might fix the problem
*** - run "make V=1", which displays the full commands invoked by make,
***   to further investigate the problem
***
make[1]: *** [advice-on-failure] Error 2
make: *** [all] Error 2
</pre></details>

From the log file 03.make, the error is due to missing file. I've attached the full file below.
```sh
Error: file-missing ("gnus/gnus-art.el" "Renaming" "No such file or directory" "/private/tmp/emacs-headA29-20230810-4819-iqwtx4/.brew_home/.emacs.d/eln-cache/29.1.50-13068817/svg-4c391752-62735252.eln" "/private/tmp/emacs-headA29-20230810-4819-iqwtx4/.brew_home/.emacs.d/eln-cache/29.1.50-13068817/svg-4c391752-62735252.elnJxxvv8.eln.tmp")
``` 

Command I ran:
```sh
brew tap daviderestivo/emacs-head
brew install emacs-head@29 --with-cocoa --with-mailutils --with-xwidgets --with-imagemagick --with-modern-icon-black-variant --with-dbus --with-native-comp --with-native-full-aot --with-tree-sitter
```

I am a bit clueless on what I can do to solve the issue, any help would be greatly appreciated 😄 

[03.make.log](https://github.com/daviderestivo/homebrew-emacs-head/files/12316267/03.make.log)

**Comment by louisdecharson** [comment]
I've tried to install it without any options, it's working but there is no "Emacs.app" file (not sure it's related to the error above)

*Output of command*

```sh
==> ./autogen.sh
==> ./configure --enable-locallisppath=/opt/homebrew/share/emacs/site-lisp --infodir=/opt/homebrew/Cellar/emacs-head@29/29.0.92_1/share/info/emacs --prefix=/opt/homebrew/Cellar/e
==> make
==> make install
==> Caveats
Emacs.app was installed to:
  /opt/homebrew/opt/emacs-head@29
To link the application:
  ln -s /opt/homebrew/opt/emacs-head@29/Emacs.app /Applications


To start daviderestivo/emacs-head/emacs-head@29 now and restart at login:
  brew services start daviderestivo/emacs-head/emacs-head@29
Or, if you don't want/need a background service you can just run:
  /opt/homebrew/opt/emacs-head@29/bin/emacs --fg-daemon
==> Summary
🍺  /opt/homebrew/Cellar/emacs-head@29/29.0.92_1: 4,198 files, 116.5MB, built in 3 minutes 21 seconds
==> Running `brew cleanup emacs-head@29`...
```

```sh
ls -l /opt/homebrew/opt/emacs-head@29/
total 128
-rw-r--r--@ 1 Louis_de_Charsonville  staff  35149 Aug 10 20:49 COPYING
-rw-r--r--@ 1 Louis_de_Charsonville  admin  10276 Aug 10 20:53 INSTALL_RECEIPT.json
-rw-r--r--@ 1 Louis_de_Charsonville  staff   6125 Aug 10 20:49 README
drwxr-xr-x@ 7 Louis_de_Charsonville  admin    224 Aug 10 20:53 bin
-rw-r--r--@ 1 Louis_de_Charsonville  admin    322 Aug 10 20:53 homebrew.emacs-head@29.service
-rw-r--r--@ 1 Louis_de_Charsonville  admin    825 Aug 10 20:53 homebrew.mxcl.emacs-head@29.plist
drwxr-xr-x@ 3 Louis_de_Charsonville  admin     96 Aug 10 20:52 include
drwxr-xr-x@ 3 Louis_de_Charsonville  admin     96 Aug 10 20:52 lib
drwxr-xr-x@ 3 Louis_de_Charsonville  admin     96 Aug 10 20:53 libexec
drwxr-xr-x@ 8 Louis_de_Charsonville  admin    256 Aug 10 20:52 share
```

**Comment by daviderestivo** [comment]
Hi @louisdecharson 

thanks to your for using emacs-head 🙂

Can you please try to reinstall using

```
brew install emacs-head@29 --with-cocoa --with-mailutils --with-xwidgets --with-imagemagick --with-modern-icon-black-variant --with-dbus --with-native-comp --with-tree-sitter
```

Regards,
Davide

**Comment by louisdecharson** [comment]
Hi David, sorry was away of my computer, just tested it and it works fine, thank you very much for your support !— Louis de Charsonville+33 6 31 49 71 ***@***.*** 15 Aug 2023, at 18:19, Davide Restivo ***@***.***> wrote:﻿
@louisdecharson did the above suggestion fixed your issue?
