### ISSUE TITLE
Compare to emacs-plus

### ISSUE THREAD

**Issue by seagle0128** [daviderestivo/homebrew-emacs-head#19]
Hi,

I'd like to know the differences between `emacs-head` and `emacs-plus`. I think many people are confused. Thanks!

**Comment by daviderestivo** [comment]
Hi @seagle0128,

The two formulas are very similar. I decided to create my own Formula some time ago because I needed some customization not present at that time on emacs-plus and because I didn’t want to depend on someone else formula. Then I decided to publish it on github if someone else would have liked to use it.

**Comment by daviderestivo** [comment]
I reopen the issue since I closed it by mistake 😀

**Comment by seagle0128** [comment]
Thanks for the quick reply, and appreciate for your great work! I am enjoy `emacs-head` now.

**Comment by daviderestivo** [comment]
@seagle0128 Thanks for using emacs-head 😀

**Comment by d12frosted** [comment]
Hey,

It's nice to see that there are more options to install Emacs on macOS. I've looked at the formula and can provide some comparison.

# `emacs-head`

`emacs-head` is basically `emacs` formula with few additional stuff (listing only stuff missing in `emacs-plus`):

- new icons

Some additional comments:

- `emacs-head` provides bottles for more macOS versions than `emacs-plus`. 
- Overall it seems that support of `emacs-head` is better 😸 I mean, @daviderestivo seems to be more responsive.

# `emacs-plus`

`emacs-plus` is basically `emacs` formula with few additional stuff (listing only stuff missing in `emacs-head`):

- `x11`
- No titlebar patch.
- New icons.
- Emacs 27 branch.
- Emacs 25 formula (just for some oldies).

Some additional comments:

- `emacs-plus` has one goal in mind - to enable all non-controversial options by default, to decrease amount of options people has to pass when installing Emacs.
- By default Spacemacs icon is installed. This is something that exists due historical reasons. I am thinking on changing that.
- Maintainer can be silent for weeks. So overall it feels like support is not as good.
- There are helpers (both in formula and scripts) to maintain the formula (if you are interested, I can elaborate a little bit more).

# Conclusion

So as you can see, these two projects are pretty much the same and differ only in few little things.

**Comment by d12frosted** [comment]
Just to keep previous comment clean and focused on comparison, I've broken it into two.

> I needed some customizations not present at that time on emacs-plus

It's pity to hear. Can you please let me know, what exactly is or was missing? You know, I am always glad to add new features, when they are needed. 

> because I didn’t want to depend on someone else formula

Oh, I understand this point very much 😸 

---

Overall, it seems like we are duplicating our efforts. Maybe we can think on how we can combine them?

**Comment by daviderestivo** [comment]
> Overall, it seems like we are duplicating our efforts. Maybe we can think on how we can combine them? I think we can help each other 😸

Ciao @d12frosted, 

First ... thanks a lot for having found the time to reply to this post 👍. 

When I started my own formula, I mostly did it for fun and for not being dependent on someone else for issues and so on.  I'm always keeping an eye on `emacs-plus` to see if you have interesting idea I can use for myself. Actually I don' even recall what I needed that at that time was not present in `emacs-plus`

On the other side it seems that there are more and more people using `emacs-head ` and I agree that we're duplicating our efforts maybe it's time now to start collaborating 😀. Whenever you have time we can find a slot to talk a bit (Skype, Zoom ... ) and see how we can proceed ... 

P.S: I do this on the spare time and let's say that I'm not a full time developer (it's more an hobby for me 😀 ).

**Comment by d12frosted** [comment]
👋 Ciao @daviderestivo 

> First ... thanks a lot for having found the time to reply to this post 👍

My pleasure. I just thought that it might be useful to share it in this topic.

> When I started my own formula, I mostly did it for fun

Haha, that's a good driver 😸 

> On the other side it seems that there are more and more people using emacs-head and I agree that we're duplicating our efforts maybe it's time now to start collaborating 😀. Whenever you have time we can find a slot to talk a bit (Skype, Zoom ... ) and see how we can proceed ...

Sure, let's do it. I will contact you via (committer) email.
