### ISSUE TITLE
 Always install imagemagick

### ISSUE THREAD

**Issue by liuyinz** [daviderestivo/homebrew-emacs-head#197]
When I install emacs without imagemagick support, the formula always install it by default.
```
brew install emacs-head@30 --with-cocoa --without-imagemagick

## Install imagemagick always
==> Fetching dependencies for daviderestivo/emacs-head/emacs-head@30: liblqr and imagemagick
```

why not set the imagemagick dependency as :optional rather than :recommend ? @daviderestivo

**Comment by daviderestivo** [comment]
Ciao @liuyinz 

lemme have a look ... 

Regards,
Davide

**Comment by daviderestivo** [comment]
Ciao @liuyinz,

I have created the following PR https://github.com/daviderestivo/homebrew-emacs-head/pull/198.
Once it builds I will merge it into master and then you can retest.

Regards,
Davide

**Comment by liuyinz** [comment]
Thanks, now it would not install imagemagick automatically on dev branch. @daviderestivo

**Comment by daviderestivo** [comment]
Actually I think it does not work. Lemme check better ...

**Comment by daviderestivo** [comment]
@liuyinz using `:optional` as you suggested does not seems to work. Compilation fails .. I tried a couple of different things unsuccessfully. So I might need more time for this issue. Thanks for your understanding.

**Comment by liuyinz** [comment]
I succeed by switch to dev branch and build emacs-head@30 ..
```
brew install emacs-head@30 --with-cocoa --with-xwidgets --with-mailutils --with-tree-sitter --with-poll
```

**Comment by daviderestivo** [comment]
@liuyinz it seems the build is 

> I succeed by switch to dev branch and build emacs-head@30 without installing imagemagick ..
> 

I see ... but the https://github.com/daviderestivo/homebrew-emacs-head/pull/198 fails to build ... I have to look why.

**Comment by daviderestivo** [comment]
Finally this issue is fixed in https://github.com/daviderestivo/homebrew-emacs-head/pull/198. 
@liuyinz can you please double check?

**Comment by liuyinz** [comment]
Thanks, @daviderestivo . worked for me in emacs@30 already.  
Another annoying issue is icons... I never use any customized icons, but everytime building emacs, I must wait all icons to download before that. Does that process could be skiped ?

**Comment by daviderestivo** [comment]
> Thanks, @daviderestivo . worked for me in emacs@30 already. 

Perfect ... I'm gonna close this issue them.

> Another annoying issue is icons... I never use any customized icons, but everytime building emacs, I must wait all icons to download before that. Does that process could be skiped ?
I will have a look to see if I can improve it ...

**Comment by daviderestivo** [comment]
@liuyinz I opened a new issue https://github.com/daviderestivo/homebrew-emacs-head/issues/199 to address the improvement of the icons handling.
