### ISSUE TITLE
support patch to enable multicolor fonts on macOS

### ISSUE THREAD

**Issue by slippycheeze** [daviderestivo/homebrew-emacs-head#2]
Emacs upstream disable multicolor font support as there is not, yet, support in the GNU/Linux rendering stack for them, so as not to have a feature on a non-free system that is not available on a free one.

It would be nice, for me, if you were to enable those with the code following, but since this is a potentially sensitive issue I preferred to send an issue than a CL.  Season the following to taste, but it is a trivial enough patch that it applies on all current versions, and has done for quite some time.

Obviously if you are not comfortable supporting this, I fully support your right to make that choice, as I support RMS upstream having the right to make this decision.

```ruby
  if build.with? "multicolor-fonts"
    patch do
      url "https://gist.githubusercontent.com/aatxe/260261daf70865fbf1749095de9172c5/raw/214b50c62450be1cbee9f11cecba846dd66c7d06/patch-multicolor-font.diff"
      sha256 "5af2587e986db70999d1a791fca58df027ccbabd75f45e4a2af1602c75511a8c"
    end
  end
```

**Comment by daviderestivo** [comment]
@slippycheeze Thanks for this patch. I have nothing against it and I will merge it over the weekend.

**Comment by daviderestivo** [comment]
@slippycheeze I have added the support to multicolour fonts. Please make a try and lemme know :)

**Comment by slippycheeze** [comment]
<3  Thanks!  Sorry for the delay in getting back, but now I'm finally back home from travel I tested it, and it works great.

**Comment by daviderestivo** [comment]
Perfect ... thanks.
