### ISSUE TITLE
provide `--debug` option that compiles with `CFLAGS=-g3` to enable crash debugging

### ISSUE THREAD

**Issue by slippycheeze** [daviderestivo/homebrew-emacs-head#20]
I've got a crash, which it'd be nice to debug.  In that vein it'd be convenient to have the exact same build as from homebrew, patches included, with debug information.  Simply providing the `-g3` flag in addition to any normal flags while calling configure would be fine, optionally disabling optimization.

Ref: https://github.com/emacs-mirror/emacs/blob/master/etc/DEBUG

**Comment by daviderestivo** [comment]
@slippycheeze that's a good idea. I'll try to do it in the as soon as I find 30 mins.

**Comment by daviderestivo** [comment]
I have added a new option `--with-crash-debug`. When enabled it adds:

- `-g3` to `CFLAGS`
- `--disable-silent-rules` to `./configure` arguments 

So, if you install emacs-head using the `--verbose` brew option:

`
brew install emacs-head --verbose --with-cocoa --with-imagemagick --with-crash-debug
`

you can have a look to the actual CFLAGS passed to the compiler:

`
clang -c  -Demacs  -I. -I. -I../lib -I../lib      -I/usr/local/Cellar/libffi/3.2.1/lib/libffi-3.2.1/include -I/usr/local/Cellar/libpng/1.6.37/include/libpng16 -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/Cellar/fontconfig/2.13.1/include -I/usr/local/Cellar/pcre/8.43/include -I/usr/local/Cellar/glib/2.62.4/include -I/usr/local/Cellar/glib/2.62.4/include/glib-2.0 -I/usr/local/Cellar/glib/2.62.4/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/pixman/0.38.4/include/pixman-1 -I/usr/local/Cellar/cairo/1.16.0_2/include/cairo -I/usr/local/Cellar/gdk-pixbuf/2.40.0/include/gdk-pixbuf-2.0 -I/usr/local/Cellar/librsvg/2.46.4/include/librsvg-2.0 -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -I/usr/local/Cellar/imagemagick@6/6.9.10-84/include/ImageMagick-6  -I/usr/local/Cellar/libxml2/2.9.10/include/libxml2       -I/usr/local/Cellar/little-cms2/2.9/include      -MMD -MF deps/macfont.d -MP  -I/usr/local/Cellar/libtasn1/4.15.0/include -I/usr/local/Cellar/nettle/3.4.1/include -I/usr/local/Cellar/p11-kit/0.23.18.1/include/p11-kit-1 -I/usr/local/Cellar/gnutls/3.6.11.1/include    -Wno-switch -Wno-pointer-sign -Wno-string-plus-int -Wno-unknown-attributes -Wno-initializer-overrides -Wno-tautological-compare -Wno-tautological-constant-out-of-range-compare -g3   macfont.m
`

**Comment by daviderestivo** [comment]
@slippycheeze Did you get a chance to try it out?

**Comment by slippycheeze** [comment]
TYVM.  There is one remaining step required to make this work: installing the (separate) debug symbol data that is generated for the application:

```
+      if build.with? "crash-debug"
+        system "dsymutil", "nextstep/Emacs.app/Contents/MacOS/Emacs"
+      end
       prefix.install "nextstep/Emacs.app"
```

Sadly, a requirement of the macOS environment.  -_-

**Comment by daviderestivo** [comment]
> TYVM. There is one remaining step required to make this work: installing the (separate) debug symbol data that is generated for the application:
[CUT]

Done ... enjoy the weekend :).
