### ISSUE TITLE
Add @SavchenkoValeriy 'Flat 3D' and 'Curvy 3D' icons

### ISSUE THREAD

**Issue by daviderestivo** [daviderestivo/homebrew-emacs-head#201]
A remainder in order to add the two new icons created by @SavchenkoValeriy:
- Flat 3D rendered icon
- Curvy 3D rendered icon

@jmckitrick you could help here if you like :)

Ref: https://github.com/SavchenkoValeriy/emacs-icons

**Comment by daviderestivo** [comment]
> @daviderestivo sure, how can I help?

You could prepare a PR to add those icons ...

**Comment by jmckitrick** [comment]
@daviderestivo Ah, ok I thought maybe it was that simple lol

**Comment by jmckitrick** [comment]
@daviderestivo So of the different resolutions he has made available for these icons, which one do I import, along with the icns file?

**Comment by jmckitrick** [comment]
@daviderestivo It looks like we use 128x128. I'm not very skilled with graphics, but that's my educated guess.

**Comment by daviderestivo** [comment]
> @daviderestivo It looks like we use 128x128. I'm not very skilled with graphics, but that's my educated guess.

Correct :)

**Comment by daviderestivo** [comment]
Fixed in https://github.com/daviderestivo/homebrew-emacs-head/pull/203

**Comment by jmckitrick** [comment]
@daviderestivo Happy to be involved!
