### ISSUE TITLE
MPS optional feature

### ISSUE THREAD

**Issue by jmckitrick** [daviderestivo/homebrew-emacs-head#213]
Would it be worth adding the new MPS GC scheme as an optional feature here, or is it too early?

**Comment by daviderestivo** [comment]
@jmckitrick why not? would you be interested in creating a PR :) ?

**Comment by jmckitrick** [comment]
Sure, as soon as I can find the instructions to build it lol. I’m still looking.Sent from my iPhoneOn Aug 17, 2024, at 8:14 AM, Davide Restivo ***@***.***> wrote:﻿
@jmckitrick why not? would you be interested in creating a PR :) ?

**Comment by jmckitrick** [comment]
@daviderestivo ok, I got the branch building from source and running in text mode. That's a big step. Last time you helped me build with a local patch. Now I need to build from a branch that is not master, and pass in a typical `--with-foo` option to the build. The last part is easy, but the first part: how do I build from a specific branch?

**Comment by jmckitrick** [comment]
@daviderestivo Wait, I think I found it. I'll report back here how it goes.

**Comment by daviderestivo** [comment]
I would try with something like the following:

``` ruby
if build.with? "mps"
  url "https://github.com/emacs-mirror/emacs.git", :branch => "scratch/igc"
else
  url "https://github.com/emacs-mirror/emacs.git"
end
```

**Comment by jmckitrick** [comment]
🤦🏻‍♂️

**Comment by daviderestivo** [comment]
Did it work as expected?

**Comment by jmckitrick** [comment]
@daviderestivo Yep! I'm running it on my work machine now. It's so smooth I need to prove to myself it's using the new GC. But I can push up a PR in a little bit.

**Comment by jmckitrick** [comment]
@daviderestivo My code is wrong. I'm working on a fix now.

**Comment by daviderestivo** [comment]
Since the feature is still not usable I close this issue.
