### ISSUE TITLE
Emacs 29 SHA mismatch

### ISSUE THREAD

**Issue by dotmilk** [daviderestivo/homebrew-emacs-head#219]
Attempting to install and getting stuck at 

https://raw.githubusercontent.com/daviderestivo/homebrew-emacs-head/master/patches/0005-System-appearance.patch

Error: emacs-head@29: SHA256 mismatch
Expected: d6ee159839b38b6af539d7b9bdff231263e451c1fd42eec0d125318c9db8cd92
     Actual: 9eb3ce80640025bff96ebaeb5893430116368d6349f4eb0cb4ef8b3d58477db6

**Comment by daviderestivo** [comment]
Try to untap the formula and tap it again 

```
brew untap daviderestivo/emacs-head
brew tap daviderestivo/emacs-head
```

then reinstall ...

**Comment by daviderestivo** [comment]
@dotmilk Did the proposed solution work?

**Comment by daviderestivo** [comment]
Closing because inactive for a month.
