### ISSUE TITLE
add posframe border support

### ISSUE THREAD

**Issue by taigacute** [daviderestivo/homebrew-emacs-head#24]
emacs mac port can show posframe border. Is it possible to add support

**Comment by daviderestivo** [comment]
Hi @taigacute,

I've tested it and I can confirm that the frame border of posframe is not show:

``` lisp
(require 'posframe)

(posframe-show "*my-posframe-buffer*"
               :string "This is a test"
               :position (point)
 :override-parameters '((internal-border-width . 5)
                        (internal-border-color . "white")
                        (background-color . "black")))

(posframe-hide-all)
```

![Screenshot 2020-02-28 at 15 58 50](https://user-images.githubusercontent.com/16867449/75559328-8c37d780-5a43-11ea-871a-3d39a99e2e63.png)

However I do not think I would be able to analyse the emacs-mac code and apply those changes to the official emacs. Sorry, but I'm not an expert of cocoa based applications.

Regards,
Davide

**Comment by taigacute** [comment]
@daviderestivo  Agree, I will review the related implementation, and I will report if there is progress

**Comment by daviderestivo** [comment]
> @daviderestivo Agree, I will review the related implementation, and I will report if there is progress

Then I leave this open until you come back to me.

**Comment by taigacute** [comment]
Thanks  should be close,when have progress i will reopen .

**Comment by daviderestivo** [comment]
@taigacute ok. Then I close it ...
