### ISSUE TITLE
Add sRGB support

### ISSUE THREAD

**Issue by abbaswasim** [daviderestivo/homebrew-emacs-head#25]
Looking at [sRGB](https://emacsredux.com/blog/2013/08/21/color-themes-redux/) build of emacs. I was looking through your formula but couldn't find anything to do with `--srgb`. Is this still possible with emacs 27 and if it will be possible to add this to the formula?

Edit: I tried to hack the `--srgb` option into the formula when using. But I am getting `configure: error: unrecognized option: --srgb`. This probably mean configure script doesn't support it anymore in which case how does one get the `--srgb` support back. Any ideas?

**Comment by abbaswasim** [comment]
I did look into this a bit further. Looking through `emacs-mirror` on GitHub I couldn't find references to `--srgb` anymore in configure scripts. However I didn't go back to check if there were any before either.

I did find `ns_use_srgb_colorspace` [here](https://github.com/emacs-mirror/emacs/blob/d77d01d22902acdc45c2c7059de4f1b158ab5806/src/nsterm.m#L9468) which by default is on for MacOs builds but the emacs 27 build I downloaded from https://emacsformacosx.com/ still has this dim color issue. Since this flag is in `nsterm.m` wondering if that's only applicable to terminal version not `cocoa` version. Not very familiar with emacs code base. ¯\_(ツ)_/¯

**Comment by daviderestivo** [comment]
Lemme have a look ...

**Comment by daviderestivo** [comment]
Hi @abbaswasim,

I did a bit of research and it seems that surge support was introduced somewhere with emacs 24. 

> ns-use-srgb-colorspace is a variable defined in ‘C source code’.
> Its value is t
> 
>   You can customize this variable.
>   This variable was introduced, or its default value was changed, in
>   version 24.4 of Emacs.
>   Probably introduced at or before Emacs version 24.4.
> 
> Documentation:
> Non-nil means to use sRGB colorspace on Mac OS X 10.7 and later.
> Note that this does not apply to images.
> This variable is ignored on Mac OS X < 10.7 and GNUstep.
> 

Now this is by default this is turned on both on emacs HEAD and it seems the same on Emacs 27.

Can you please tell me the installation option you have used to install emacs-head?

In addition can you please tell me the value of this variable `ns-use-srgb-colorspace` on your system?

**Comment by abbaswasim** [comment]
I installed it with this command:

`brew install emacs-head --verbose --HEAD --with-cocoa --with-imagemagick --with-jansson`

That installs:
```
GNU Emacs 28.0.50 (build 1, x86_64-apple-darwin19.4.0, NS appkit-1894.40 Version 10.15.4 (Build 19E287)) of 2020-05-05
```
Its `describe-var` at `ns-use-srgb-colorspace` gives:
```
ns-use-srgb-colorspace is a variable defined in ‘C source code’.
Its value is nil
Original value was t

  You can customize this variable.


This variable was introduced, or its default value was changed, in
version 24.4 of Emacs.
  Probably introduced at or before Emacs version 24.4.

Documentation:
Non-nil means to use sRGB colorspace on Mac OS X 10.7 and later.
Note that this does not apply to images.
This variable is ignored on Mac OS X < 10.7 and GNUstep.
```

And here is the value for `ns-use-srgb-colorspace` for reference in the other emacs 26 that I have downloaded from emacs Mac port (might be relevant)

```
ns-use-srgb-colorspace’s value is nil

Documentation:
Not documented as a variable.
```

**Comment by abbaswasim** [comment]
Having looked at this again I was sure I tried setting this to true like `(setq ns-use-srgb-colorspace t)` in my init files. But that doesn't seem to take effect.

**Comment by daviderestivo** [comment]
@abbaswasim sorry for asking maybe something obvious :):

- On emacs-head 28.0.50 is the color rendering fine?
- You can install emacs-head 26.3 simply using: `brew install emacs-head`. This will install emacs 26.3. Can you check if the color rendering is ok or broken?
- I assume you're using macOS newer than 10.7 :)

**Comment by abbaswasim** [comment]
@daviderestivo no problem happy to provide any info you need to debug this.

> On emacs-head 28.0.50 is the color rendering fine?

No. The screenshots I provided you can see the emacs version as well as color. Its brighter than the emacs from Mac-port (26.3) on the right with darker colors.

> You can install emacs-head 26.3 simply using: brew install emacs-head. This will install emacs 26.3. Can you check if the color rendering is ok or broken?

<img width="1369" alt="Screenshot 2020-05-06 at 12 30 55" src="https://user-images.githubusercontent.com/5260991/81172068-72f85d80-8f95-11ea-8fb3-8a3d0b7d06ff.png">

<img width="1369" alt="Screenshot 2020-05-06 at 12 31 29" src="https://user-images.githubusercontent.com/5260991/81172106-86a3c400-8f95-11ea-947c-989ddae5bff0.png">

On the left is: `Emacs 26.3 (build 1, x86_64-apple-darwin19.2.0, NS appkit-1894.20 Version 10.15.2 (Build 19C57)) of 2020-01-07` Freshly installed with `brew install emacs-head`. On the right is `GNU Emacs 26.3 (build 1, x86_64-apple-darwin18.5.0, Carbon Version 158 AppKit 1671.4) of 2019-08-29` from macport.

> I assume you're using macOS newer than 10.7 :)

Thats correct. Catalina 10.15.4 also mentioned in the `emacs-version` I posted up there.

**Comment by abbaswasim** [comment]
I have realised this comparison might not be right. The `emacs-head` version is using `NS appkit` while the `macport` one is `Carbon`. The color difference might be coming from there.. But either way if you see in the screenshots for `emacs-head` even the power line characters has the same issue.

**Comment by abbaswasim** [comment]
bingo 😄 

If I set the `ns-use-srgb-colorspace` with `customise-variable`. Its originally `non-nil` or `on` which is correct behaviour but it doesn't work. I had to turn it `nil` and then again `non-nil` to make it work. 

`(setq ns-use-srgb-colorspace t)` in the init files has no effect which is strange or I might be doing something silly.

The bellow config works. Producing correct colors.

```
Hide Ns Use Srgb Colorspace: Toggle  on (non-nil)
    State : SAVED and set.
   Non-nil means to use sRGB colorspace on Mac OS X 10.7 and later. Hide
   Note that this does not apply to images.
   This variable is ignored on Mac OS X < 10.7 and GNUstep.
Groups: Ns
```

**Comment by abbaswasim** [comment]
@daviderestivo I think there is another bad news 😢 I think homebrew has just broken formula specific cli options. On master right now you can't pass any of the arguments to `brew install emacs-head` apart from `--HEAD` only. `--with-cocoa` or `--with-imagemagick` etc are all flagged as `brew` command options and it complains saying unrecognised option or something like that.

**Comment by daviderestivo** [comment]
> @daviderestivo I think there is another bad news 😢 I think homebrew has just broken formula specific cli options. 

I think the right command is:

`brew install --debug emacs-head  --HEAD --with-cocoa --with-imagemagick --with-jansson`

`--debug` is a brew option itself not a `./configure` option. You cannot pass  arbitrary `'--' `options not specified in the formula. If you want to see the different phases of the installation (`./configure; make; make install`) you can use:

`brew install --verbose --debug emacs-head  --HEAD --with-cocoa --with-imagemagick --with-jansson`

Regarding the original question: sRGB is support is enabled by default. As you have already spotted the fact that the emacs macport version colours are darker than the one of emacs-head is because **emacs-head** version uses `NS appkit` while the **macport** one is using `Carbon`.

I do not think there too much I can do here :).

**Comment by abbaswasim** [comment]
> `--debug` is a brew option itself not a ./configure option.
I know. Have a look at the bug I reported at `brew` its not about the `--debug` picked wrongly. Brew is actually promoting _any_ arguments after `--HEAD` to itself rather passing it on to the `formula`. At the moment putting `--debug` _anywhere_ doesn't matter. Brew will pick it up. Either way that's not the issue. The issue is you can't pass any arguments to any formula anymore not specific to your formula.

> sRGB is support is enabled by default

**Comment by daviderestivo** [comment]
>The issue is you can't pass any arguments to any formula anymore not specific to your formula.

Ok .. I got it now.

> > sRGB is support is enabled by default
> 
> Thats true. But it's not _on_ by default. you still have to do `(ns-use-srgb-colorspace t)` in your `init.el` for it to be enabled. Not sure who needs to fix that issue. Or if that's the default behaviour then you are right nothing else to do.

It's enabled by default in my setup without any explicit config in `init.el`. So If you agree I would close this issue :). Thanks for the interesting info you brought in this issue.

**Comment by abbaswasim** [comment]
> It's enabled by default in my setup without any explicit config in init.el

Ah interesting. It would be worth investigating why. But I guess less urgent. Thanks for your support.
