### ISSUE TITLE
Possible to support 27 branch?

### ISSUE THREAD

**Issue by dangom** [daviderestivo/homebrew-emacs-head#29]
I would like to install Emacs 27 with a --devel flag, but not Emacs 28 with --head. How much work would it be to add such a flag? I guess the same config parameters that --head accepts should work with --devel.

**Comment by daviderestivo** [comment]
Hi @dangom,

thanks for your interest in emacs-head. I can have a look in what it means to support emacs 27. The main complication I see at the moment is porting all of the current patches from Emacs HEAD to Emacs 27 branch. I will keep you posted.

Regards,
Davide

**Comment by daviderestivo** [comment]
Hi @dangom,

a quick update. I decided to add support to Emacs 27 as well. The main point is that this would require to restructure this formula and split it into three different ones:

```
emacs-head
emacs-head@27
emacs-head@28
```

The main reasons for this splitting are:
- `devel` is deprecated in homebrew and might be removed soon
-  `if ... else ...end` checking might became very nasty 

Said that, I hope to have something usable in the upcoming days.

Regards,
Davide

**Comment by dangom** [comment]
Thanks for taking your time to support the feature request!
I imagine this will be useful to all Emacsen who want to use 27 because of the multitude of performance improvements, but still keep compatibility with most MELPA packages out there.

**Comment by daviderestivo** [comment]
[Build](https://travis-ci.com/github/daviderestivo/homebrew-emacs-head/builds/171195415) is successful :).

Merged  [PR30](https://github.com/daviderestivo/homebrew-emacs-head/pull/30) into master.

Have fun :)
