### ISSUE TITLE
A doubt with --gnu-tls option

### ISSUE THREAD

**Issue by anquegi** [daviderestivo/homebrew-emacs-head#4]
First of all thanks for this, you literally save my life working with mac ;-)

I cannot see the old gnu-tls option. It is not needed for emacs 27.x  (HEAD).

I need de gnu-tls dependency in order to import some packages from repositories with cask. but it seems to work well after installation

```
ELISP> (gnutls-available-p)
(ClientHello\ Padding Key\ Share Post\ Handshake\ Auth PSK\ Key\ Exchange\ Modes Cookie Supported\ Versions Early\ Data Pre\ Shared\ Key Session\ Ticket Record\ Size\ Limit Extended\ Master\ Secret Encrypt-then-MAC ClientHello\ Padding Server\ Certificate\ Type Client\ Certificate\ Type ALPN SRTP Signature\ Algorithms SRP Supported\ EC\ Point\ Formats Supported\ Groups OCSP\ Status\ Request Maximum\ Record\ Size Server\ Name\ Indication macs AEAD-ciphers ciphers digests gnutls3 gnutls)
```

**Comment by daviderestivo** [comment]
Ciao @anquegi,

gnutls option was enabled by default. I think it should be configurable using --with-gnutls. I updated the formula to reflect this https://github.com/daviderestivo/homebrew-emacs-head/pull/5.

Regards,
Davide

**Comment by anquegi** [comment]
Thanks for your quick reply and fix, I will close this issue now

**Comment by daviderestivo** [comment]
Thanks to you for spotting this issue.

**Comment by daviderestivo** [comment]
In order to create a bottle for Mojave I had to mangle a bit with the dependencies. From now on GnuTLS is enabled by default. If you want to disable it please use —without-gnutls.
