### ISSUE TITLE
Update 0005-System-appearance.patch to the newest version?

### ISSUE THREAD

**Issue by wd** [daviderestivo/homebrew-emacs-head#57]
I'm not sure if the patch comes from [here](https://github.com/d12frosted/homebrew-emacs-plus/blob/master/patches/emacs-28/system-appearance.patch) , but seems there is an important fix for `posframe` users [this PR](https://github.com/d12frosted/homebrew-emacs-plus/pull/242), and [this issue](https://github.com/d12frosted/homebrew-emacs-plus/issues/240), can we sync the patch with that repo?

**Comment by daviderestivo** [comment]
Hi @wd 

Thanks for this info. I will have a look as soon as possible.

Regards,
Davide

**Comment by daviderestivo** [comment]
Fixed in  pull request #58.

**Comment by daviderestivo** [comment]
... and pull request #60. Sorry I forgot to update the resource shasum.
