### ISSUE TITLE
Not all icons work for 28

### ISSUE THREAD

**Issue by jmckitrick** [daviderestivo/homebrew-emacs-head#75]
I’ve been trying different icons, and I’ve noticed some do not work. The most recent is modern-icon-orange. Oddly enough, the file ends up in the version 27 build folders, but not in 28, and I end up with the same icon I built with before.

Aside from this issue, is there an easier way to swap icons rather than a complete brew uninstall and install with the new icon? It takes 10 minutes to build and try an icon, so I haven’t had time to try others yet.

**Comment by daviderestivo** [comment]
Hi @jmckitrick,

thanks for reporting this issue. I have fixed it in https://github.com/daviderestivo/homebrew-emacs-head/pull/77. I didn't find a way to change the icons after Emacs is installed. Replacing `Emacs.icns` it in `/Applications/Emacs.app/Contents/Resources/` does not seems to work.

Regards,
Davide
