### ISSUE TITLE
native-compile-setup-environment-variables function report error with native comp build

### ISSUE THREAD

**Issue by wd** [daviderestivo/homebrew-emacs-head#81]
```
Debugger entered--Lisp error: (file-missing "Opening directory" "No such file or directory" "/usr/local/Cellar/emacs-head@28/28.0.50_1/Emacs.app/Contents/MacOS/lib/gcc")
  native-compile-setup-environment-variables("/Users/wd/.emacs.d/elpa/diminish-20191127.1326" t)
```

I have checked, there is no `/usr/local/Cellar/emacs-head@28/28.0.50_1/Emacs.app/Contents/MacOS/lib` directory exits.

I see this function was added through this patch: https://github.com/daviderestivo/homebrew-emacs-head/pull/79/files#diff-7559cf19008a5b1f3889d64ea7f078c04ed22f4954a251d921c6dfaa340faee7

Emacs build command: `brew install emacs-head@28 --with-cocoa --with-no-frame-refocus --with-modern-icon-bokehlicia-captiva --with-xwidgets --with-pdumper --with-native-comp`

**Comment by daviderestivo** [comment]
This problem should be fixed by the patch mentioned here: https://github.com/d12frosted/homebrew-emacs-plus/issues/187#issuecomment-750227966

I have just included it in the dev branch. Once all CI checks are done successfully I will merge it into master.

**Comment by wd** [comment]
Ah I see, I was trying to create a symbol link for the directory but didn't find the right source directory. Now I know how to do that.
```
ln -s /usr/local/opt/gcc/lib /usr/local/Cellar/emacs-head@28/28.0.50_1/Emacs.app/Contents/MacOS
```

Close this issue
