### ISSUE TITLE
Signature of function define-obsolete-function-alias changed?

### ISSUE THREAD

**Issue by pragmat1c1** [daviderestivo/homebrew-emacs-head#88]
Today I reinstalled Emacs from your tap, and suddenly I get this error: `Error: Wrong number of arguments: (3 . 4), 2`

Going in to the details (see [1]) I realized that  the signature of the function `define-obsolete-function-alias` has changed in Emacs `28.0.50` from two required arguments to three (adding `when`).

Now many packages stop compiling as they have lines  like this, with 2 arguments instead of 3:

    (define-obsolete-function-alias 'org-journal-open-next-entry 'org-journal-next-entry)

## Previous signature of the function

    (defun make-obsolete-variable (obsolete-name current-name &optional when access-type)

`when` is optional

## Current signature of the function

    (defun make-obsolete-variable (obsolete-name current-name when &optional access-type)

## Consequences

This breaks many packages when trying to compile. For instance `slime`, but many others.

---
[1] https://www.reddit.com/r/emacs/comments/kqb9s9/cannot_recompile_packagess_error_wrong_number_of/

**Comment by daviderestivo** [comment]
@pragmat1c1 Thanks for reporting this issue.

**Comment by ccakes** [comment]
Not a fix as such, but [this Reddit post](https://www.reddit.com/r/emacs/comments/kqd9wi/changes_in_emacshead2828050_break_many_packages/gitmpy2?utm_source=share&utm_medium=web2x&context=3) has a functional workaround

**Comment by daviderestivo** [comment]
Since most of the package maintainers already have replaced `define-obsolete-function-alias` with the new one. I guess e can close this issue.
