### ISSUE TITLE
emacs-head@28: No such file or directory - native-lisp

### ISSUE THREAD

**Issue by farynaio** [daviderestivo/homebrew-emacs-head#93]
When building with `brew install emacs-head@28 --with-cocoa --with-dbus --with-no-frame-refocus --with-imagemagick --with-pdumper  --with-xwidgets --with-native-comp` I get:

```bash
...
==> ./configure --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-head@28/28.0.50_1/share/info/emacs --prefix=/usr/local
==> make BYTE_COMPILE_EXTRA_FLAGS=--eval '(setq comp-speed 2)'
==> make install
Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory - native-lisp
```

**Comment by daviderestivo** [comment]
@farynaio it should be fixed in https://github.com/daviderestivo/homebrew-emacs-head/pull/94. Please try again and lemme me know.

**Comment by farynaio** [comment]
It's working now, thanks!

**Comment by Bounga** [comment]
I do have the exact same problem and brew is up to date

**Comment by daviderestivo** [comment]
Have you tried to untap and tap the formula once again:

```
brew untap daviderestivo/emacs-head
brew tap daviderestivo/emacs-head
```

Done that try to install Emacs-head

**Comment by Bounga** [comment]
It worked! Thanks a lot
